# Generated by Django 3.2.4 on 2021-07-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=100)),
                ('grouping', models.CharField(max_length=150)),
                ('grouping_label', models.CharField(max_length=200)),
                ('account_name', models.CharField(max_length=250)),
                ('account_name_label', models.CharField(max_length=200)),
                ('context', models.CharField(max_length=50)),
                ('value', models.IntegerField()),
                ('unit', models.CharField(max_length=50)),
            ],
        ),
    ]
